name: Test
on:
  - push
  - pull_request
permissions:
  contents: read
jobs:
  go-tests:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run tests
        run: go test -v ./...
