name: Test
on:
  - push
  - pull_request
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  go-tests:
    name: Go tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Check Go formatting
        run: go fmt ./... && git diff --exit-code
      - name: Check go.mod
        run: go mod tidy && git diff --exit-code
      - name: Run tests
        run: go test -race -shuffle on ./...
